project:
  type: website
  output-dir: docs

website:
  favicon: ./images/user_favicon.png
  navbar:
    logo: ./images/user_favicon.png
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: books.qmd
        text: Books
      - href: reflection.qmd
        text: Reflection on GenAI

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



